# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='CallPredict',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ndata.proto\x12\x0b\x43\x61llPredict\"\x8e\x07\n\x07Request\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\x12\x14\n\x0cprotocolType\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\r\x12\x0c\n\x04\x66lag\x18\x04 \x01(\r\x12\x10\n\x08srcBytes\x18\x05 \x01(\r\x12\x10\n\x08\x64stBytes\x18\x06 \x01(\r\x12\x0c\n\x04land\x18\x07 \x01(\r\x12\x15\n\rwrongFragment\x18\x08 \x01(\r\x12\x0e\n\x06urgent\x18\t \x01(\r\x12\x0c\n\x04host\x18\n \x01(\r\x12\x17\n\x0fnumFailedLogins\x18\x0b \x01(\r\x12\x10\n\x08loggedIn\x18\x0c \x01(\r\x12\x16\n\x0enumCompromised\x18\r \x01(\r\x12\x11\n\trootShell\x18\x0e \x01(\r\x12\x13\n\x0bsuAttempted\x18\x0f \x01(\r\x12\x0f\n\x07numRoot\x18\x10 \x01(\r\x12\x18\n\x10numFileCreations\x18\x11 \x01(\r\x12\x11\n\tnumShells\x18\x12 \x01(\r\x12\x16\n\x0enumAccessFiles\x18\x13 \x01(\r\x12\x17\n\x0fnumOutboundCmds\x18\x14 \x01(\r\x12\x12\n\nisHotLogin\x18\x15 \x01(\r\x12\x14\n\x0cisGuestLogin\x18\x16 \x01(\r\x12\r\n\x05\x63ount\x18\x17 \x01(\r\x12\x10\n\x08srvCount\x18\x18 \x01(\r\x12\x12\n\nsErrorRate\x18\x19 \x01(\x02\x12\x15\n\rsrvSErrorRate\x18\x1a \x01(\x02\x12\x12\n\nrErrorRate\x18\x1b \x01(\x02\x12\x15\n\rsrvRErrorRate\x18\x1c \x01(\x02\x12\x13\n\x0bsameSrvRate\x18\x1d \x01(\x02\x12\x13\n\x0b\x64iffSrvRate\x18\x1e \x01(\x02\x12\x17\n\x0fsrvDiffHostRate\x18\x1f \x01(\x02\x12\x14\n\x0c\x64stHostCount\x18  \x01(\r\x12\x17\n\x0f\x64stHostSrvCount\x18! \x01(\r\x12\x1a\n\x12\x64stHostSameSrvRate\x18\" \x01(\x02\x12\x1a\n\x12\x64stHostDiffSrvRate\x18# \x01(\x02\x12\x1e\n\x16\x64stHostSameSrcPortRate\x18$ \x01(\x02\x12\x1e\n\x16\x64stHostSrvDiffHostRate\x18% \x01(\x02\x12\x19\n\x11\x64stHostSErrorRate\x18& \x01(\x02\x12\x1c\n\x14\x64stHostSrvSErrorRate\x18\' \x01(\x02\x12\x19\n\x11\x64stHostRErrorRate\x18( \x01(\x02\x12\x1c\n\x14\x64stHostSrvRErrorRate\x18) \x01(\x02\"\x19\n\x08Response\x12\r\n\x05label\x18\x01 \x01(\r2G\n\x0bPredictFlow\x12\x38\n\x07predict\x12\x14.CallPredict.Request\x1a\x15.CallPredict.Response\"\x00\x62\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='CallPredict.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='CallPredict.Request.duration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocolType', full_name='CallPredict.Request.protocolType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='CallPredict.Request.service', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='CallPredict.Request.flag', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srcBytes', full_name='CallPredict.Request.srcBytes', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstBytes', full_name='CallPredict.Request.dstBytes', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='land', full_name='CallPredict.Request.land', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wrongFragment', full_name='CallPredict.Request.wrongFragment', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='urgent', full_name='CallPredict.Request.urgent', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='CallPredict.Request.host', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numFailedLogins', full_name='CallPredict.Request.numFailedLogins', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loggedIn', full_name='CallPredict.Request.loggedIn', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numCompromised', full_name='CallPredict.Request.numCompromised', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rootShell', full_name='CallPredict.Request.rootShell', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suAttempted', full_name='CallPredict.Request.suAttempted', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numRoot', full_name='CallPredict.Request.numRoot', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numFileCreations', full_name='CallPredict.Request.numFileCreations', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numShells', full_name='CallPredict.Request.numShells', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numAccessFiles', full_name='CallPredict.Request.numAccessFiles', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numOutboundCmds', full_name='CallPredict.Request.numOutboundCmds', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isHotLogin', full_name='CallPredict.Request.isHotLogin', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isGuestLogin', full_name='CallPredict.Request.isGuestLogin', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='CallPredict.Request.count', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srvCount', full_name='CallPredict.Request.srvCount', index=23,
      number=24, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sErrorRate', full_name='CallPredict.Request.sErrorRate', index=24,
      number=25, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srvSErrorRate', full_name='CallPredict.Request.srvSErrorRate', index=25,
      number=26, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rErrorRate', full_name='CallPredict.Request.rErrorRate', index=26,
      number=27, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srvRErrorRate', full_name='CallPredict.Request.srvRErrorRate', index=27,
      number=28, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sameSrvRate', full_name='CallPredict.Request.sameSrvRate', index=28,
      number=29, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diffSrvRate', full_name='CallPredict.Request.diffSrvRate', index=29,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='srvDiffHostRate', full_name='CallPredict.Request.srvDiffHostRate', index=30,
      number=31, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostCount', full_name='CallPredict.Request.dstHostCount', index=31,
      number=32, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostSrvCount', full_name='CallPredict.Request.dstHostSrvCount', index=32,
      number=33, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostSameSrvRate', full_name='CallPredict.Request.dstHostSameSrvRate', index=33,
      number=34, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostDiffSrvRate', full_name='CallPredict.Request.dstHostDiffSrvRate', index=34,
      number=35, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostSameSrcPortRate', full_name='CallPredict.Request.dstHostSameSrcPortRate', index=35,
      number=36, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostSrvDiffHostRate', full_name='CallPredict.Request.dstHostSrvDiffHostRate', index=36,
      number=37, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostSErrorRate', full_name='CallPredict.Request.dstHostSErrorRate', index=37,
      number=38, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostSrvSErrorRate', full_name='CallPredict.Request.dstHostSrvSErrorRate', index=38,
      number=39, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostRErrorRate', full_name='CallPredict.Request.dstHostRErrorRate', index=39,
      number=40, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dstHostSrvRErrorRate', full_name='CallPredict.Request.dstHostSrvRErrorRate', index=40,
      number=41, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=938,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='CallPredict.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='CallPredict.Response.label', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=940,
  serialized_end=965,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:CallPredict.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:CallPredict.Response)
  })
_sym_db.RegisterMessage(Response)



_PREDICTFLOW = _descriptor.ServiceDescriptor(
  name='PredictFlow',
  full_name='CallPredict.PredictFlow',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=967,
  serialized_end=1038,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='CallPredict.PredictFlow.predict',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTFLOW)

DESCRIPTOR.services_by_name['PredictFlow'] = _PREDICTFLOW

# @@protoc_insertion_point(module_scope)
